# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-01-24 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20170124_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='common.Todo', verbose_name='Работа'),
        ),
    ]
