# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-02 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Код'),
        ),
    ]
