export const GET_STATUSES_REQUEST =  'GET_STATUSES_REQUEST';
export const GET_STATUSES_FAIL =     'GET_STATUSES_FAIL';
export const GET_STATUSES_SUCCESS =  'GET_STATUSES_SUCCESS';

export const POST_STATUS_REQUEST =   'POST_STATUS_REQUEST';
export const POST_STATUS_SUCCESS =   'POST_STATUS_SUCCESS';
export const POST_STATUS_FAIL =      'POST_STATUS_FAIL';

export const CHANGE_STATUS_CREATED = 'CHANGE_STATUS_CREATED';

export const DELETE_STATUS_REQUEST = 'DELETE_STATUS_REQUEST';
export const DELETE_STATUS_SUCCESS = 'DELETE_STATUS_SUCCESS';
export const DELETE_STATUS_FAIL =    'DELETE_STATUS_FAIL';